import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import vue3Plugin from "esbuild-plugin-vue3";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

import fs from "fs";

const cssMergePlugin = {
    name: "css-merge",
    setup(build) {
        build.onEnd(() => {
            try {
                const globalCss = fs.existsSync("src/styles.css") ? fs.readFileSync("src/styles.css", "utf8") : "";
                const vueCss = fs.existsSync("main.css") ? fs.readFileSync("main.css", "utf8") : "";
                fs.writeFileSync("styles.css", globalCss + "\n" + vueCss);
                console.log("⚡ [esbuild] styles.css merged successfully!");
            } catch (err) {
                console.error("Error merging CSS files:", err);
            }
        });
    }
};

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins
    ],
    plugins: [vue3Plugin(), cssMergePlugin],
    format: "cjs",
    target: "es2020",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}