import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import vue3Plugin from "esbuild-plugin-vue3";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

import fs from "fs";
import path from "path";

const cssMergePlugin = {
    name: "css-merge",
    setup(build) {
        build.onEnd(() => {
            try {
                const globalCss = fs.existsSync("src/styles.css") ? fs.readFileSync("src/styles.css", "utf8") : "";
                const vueCss = fs.existsSync("main.css") ? fs.readFileSync("main.css", "utf8") : "";
                fs.writeFileSync("styles.css", globalCss + "\n" + vueCss);
                console.log("⚡ [esbuild] styles.css merged successfully!");
            } catch (err) {
                console.error("Error merging CSS files:", err);
            }
        });
    }
};

const wasmCopyPlugin = {
    name: "wasm-copy",
    setup(build) {
        build.onEnd(() => {
            try {
                // 创建 dist 目录（如果不存在）
                const distDir = path.join(process.cwd(), "dist");
                if (!fs.existsSync(distDir)) {
                    fs.mkdirSync(distDir, { recursive: true });
                }

                // 拷贝 onnxruntime-web WASM 文件
                const onnxSrcDir = path.join(process.cwd(), "node_modules", "onnxruntime-web", "dist");
                if (fs.existsSync(onnxSrcDir)) {
                    const wasmFiles = fs.readdirSync(onnxSrcDir).filter(f => f.endsWith(".wasm") || f.endsWith(".jsep.js"));
                    wasmFiles.forEach(file => {
                        const src = path.join(onnxSrcDir, file);
                        const dest = path.join(distDir, file);
                        fs.copyFileSync(src, dest);
                    });
                    console.log(`⚡ [esbuild] Copied ${wasmFiles.length} WASM files to dist/`);
                }
            } catch (err) {
                console.error("Error copying WASM files:", err);
            }
        });
    }
};

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins
    ],
    plugins: [vue3Plugin(), cssMergePlugin, wasmCopyPlugin],
    format: "cjs",
    target: "es2020",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}