import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import vue3Plugin from "esbuild-plugin-vue3";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

import fs from "fs";
import path from "path";

const cssMergePlugin = {
    name: "css-merge",
    setup(build) {
        build.onEnd(() => {
            try {
                const globalCss = fs.existsSync("src/styles.css") ? fs.readFileSync("src/styles.css", "utf8") : "";
                const vueCss = fs.existsSync("main.css") ? fs.readFileSync("main.css", "utf8") : "";
                fs.writeFileSync("styles.css", globalCss + "\n" + vueCss);
                console.log("⚡ [esbuild] styles.css merged successfully!");
            } catch (err) {
                console.error("Error merging CSS files:", err);
            }
        });
    }
};

const wasmCopyPlugin = {
    name: "wasm-copy",
    setup(build) {
        build.onEnd(() => {
            try {
                // 创建 dist 目录（如果不存在）
                const distDir = path.join(process.cwd(), "dist");
                if (!fs.existsSync(distDir)) {
                    fs.mkdirSync(distDir, { recursive: true });
                }

                // 拷贝 onnxruntime-web WASM/MJS/JS 文件
                const onnxSrcDir = path.join(process.cwd(), "node_modules", "onnxruntime-web", "dist");
                if (fs.existsSync(onnxSrcDir)) {
                    const files = fs.readdirSync(onnxSrcDir).filter(f => f.endsWith(".wasm") || f.endsWith(".mjs") || f.endsWith(".js"));
                    files.forEach(file => {
                        const src = path.join(onnxSrcDir, file);
                        const dest = path.join(distDir, file);
                        
                        if (file.endsWith(".mjs") || file.endsWith(".js")) {
                            // 读取内容并替换以解决浏览器/Obsidian沙盒不支持 Node.js 模块的问题，并强制运行在纯浏览器模式下
                            let content = fs.readFileSync(src, "utf8");
                            content = content.replace(/globalThis\.process\?\.versions\?\.node/g, "false");
                            content = content.replace(/require\(['"]worker_threads['"]\)/g, "({ Worker: typeof Worker !== 'undefined' ? Worker : null, workerData: null })");
                            content = content.replace(/import\(['"]worker_threads['"]\)/g, "Promise.resolve({ Worker: typeof Worker !== 'undefined' ? Worker : null, workerData: null })");
                            content = content.replace(/import\(['"]module['"]\)/g, "Promise.resolve({ createRequire: () => () => ({}) })");
                            content = content.replace(/import\s*\{\s*createRequire\s*\}\s*from\s*['"]module['"]/g, "const createRequire = () => () => ({});");
                            fs.writeFileSync(dest, content, "utf8");
                        } else {
                            fs.copyFileSync(src, dest);
                        }
                    });
                    console.log(`⚡ [esbuild] Copied and patched ${files.length} ONNX runtime files to dist/`);
                }
            } catch (err) {
                console.error("Error copying WASM files:", err);
            }
        });
    }
};

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins
    ],
    plugins: [vue3Plugin(), cssMergePlugin, wasmCopyPlugin],
    format: "cjs",
    target: "es2020",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
});

const workerContext = await esbuild.context({
    entryPoints: ["src/workers/whisper-worker.ts"],
    bundle: true,
    platform: "browser",
    format: "iife",
    target: "es2020",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "whisper-worker.js",
});

if (prod) {
    await context.rebuild();
    await workerContext.rebuild();
    process.exit(0);
} else {
    await context.watch();
    await workerContext.watch();
}