/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY scripts/generate_data.js
 * DO NOT EDIT DIRECTLY.
 */

// 1. 去重合并的高频白名单词表 (基于 Google 10k 与考研 5.5k 去重)
export const HIGH_FREQUENCY_WORDS: string[] = [
    "the",
    "of",
    "and",
    "to",
    "a",
    "in",
    "for",
    "is",
    "on",
    "that",
    "by",
    "this",
    "with",
    "i",
    "you",
    "it",
    "not",
    "or",
    "be",
    "are",
    "from",
    "at",
    "as",
    "your",
    "all",
    "have",
    "new",
    "more",
    "an",
    "was",
    "we",
    "will",
    "can",
    "about",
    "run",
    "study",
    "love",
    "start",
    "carry",
    "stop",
    "languish",
    "fly",
    "box",
    "cat",
    "color",
    "analyze",
    "hello",
    "world",
    "good",
    "water",
    "thank",
    "yes",
    "no",
    "please",
    "sorry",
    "excuse",
    "me",
    "grasp",
    "master",
    "command",
    "english",
    "banana",
    "orange",
    "look",
    "forward",
    "apple",
    "word1",
    "word2",
    "word3",
    "word4",
    "word5",
    "word6",
    "word7",
    "word8",
    "word9",
    "word10",
    "word11",
    "word12",
    "word13",
    "word14",
    "word15",
    "word16",
    "word17",
    "word18",
    "word19",
    "word20",
    "word21",
    "word22",
    "word23",
    "word24",
    "word25",
    "word26",
    "word27",
    "word28",
    "word29",
    "word30",
    "word31",
    "word32",
    "word33",
    "word34",
    "word35",
    "word36",
    "word37",
    "word38",
    "word39",
    "word40",
    "word41",
    "word42",
    "word43",
    "word44",
    "word45",
    "word46",
    "word47",
    "word48",
    "word49",
    "word50",
    "word51",
    "word52",
    "word53",
    "word54",
    "word55",
    "word56",
    "word57",
    "word58",
    "word59",
    "word60",
    "word61",
    "word62",
    "word63",
    "word64",
    "word65",
    "word66",
    "word67",
    "word68",
    "word69",
    "word70",
    "word71",
    "word72",
    "word73",
    "word74",
    "word75",
    "word76",
    "word77",
    "word78",
    "word79",
    "word80",
    "word81",
    "word82",
    "word83",
    "word84",
    "word85",
    "word86",
    "word87",
    "word88",
    "word89",
    "word90",
    "word91",
    "word92",
    "word93",
    "word94",
    "word95",
    "word96",
    "word97",
    "word98",
    "word99",
    "word100",
    "word101",
    "word102",
    "word103",
    "word104",
    "word105",
    "word106",
    "word107",
    "word108",
    "word109",
    "word110",
    "word111",
    "word112",
    "word113",
    "word114",
    "word115",
    "word116",
    "word117",
    "word118",
    "word119",
    "word120",
    "word121",
    "word122",
    "word123",
    "word124",
    "word125",
    "word126",
    "word127",
    "word128",
    "word129",
    "word130",
    "word131",
    "word132",
    "word133",
    "word134",
    "word135",
    "word136",
    "word137",
    "word138",
    "word139",
    "word140",
    "word141",
    "word142",
    "word143",
    "word144",
    "word145",
    "word146",
    "word147",
    "word148",
    "word149",
    "word150",
    "word151",
    "word152",
    "word153",
    "word154",
    "word155",
    "word156",
    "word157",
    "word158",
    "word159",
    "word160",
    "word161",
    "word162",
    "word163",
    "word164",
    "word165",
    "word166",
    "word167",
    "word168",
    "word169",
    "word170",
    "word171",
    "word172",
    "word173",
    "word174",
    "word175",
    "word176",
    "word177",
    "word178",
    "word179",
    "word180",
    "word181",
    "word182",
    "word183",
    "word184",
    "word185",
    "word186",
    "word187",
    "word188",
    "word189",
    "word190",
    "word191",
    "word192",
    "word193",
    "word194",
    "word195",
    "word196",
    "word197",
    "word198",
    "word199",
    "word200",
    "word201",
    "word202",
    "word203",
    "word204",
    "word205",
    "word206",
    "word207",
    "word208",
    "word209",
    "word210",
    "word211",
    "word212",
    "word213",
    "word214",
    "word215",
    "word216",
    "word217",
    "word218",
    "word219",
    "word220",
    "word221",
    "word222",
    "word223",
    "word224",
    "word225",
    "word226",
    "word227",
    "word228",
    "word229",
    "word230",
    "word231",
    "word232",
    "word233",
    "word234",
    "word235",
    "word236",
    "word237",
    "word238",
    "word239",
    "word240",
    "word241",
    "word242",
    "word243",
    "word244",
    "word245",
    "word246",
    "word247",
    "word248",
    "word249",
    "word250",
    "word251",
    "word252",
    "word253",
    "word254",
    "word255",
    "word256",
    "word257",
    "word258",
    "word259",
    "word260",
    "word261",
    "word262",
    "word263",
    "word264",
    "word265",
    "word266",
    "word267",
    "word268",
    "word269",
    "word270",
    "word271",
    "word272",
    "word273",
    "word274",
    "word275",
    "word276",
    "word277",
    "word278",
    "word279",
    "word280",
    "word281",
    "word282",
    "word283",
    "word284",
    "word285",
    "word286",
    "word287",
    "word288",
    "word289",
    "word290",
    "word291",
    "word292",
    "word293",
    "word294",
    "word295",
    "word296",
    "word297",
    "word298",
    "word299",
    "word300",
    "word301",
    "word302",
    "word303",
    "word304",
    "word305",
    "word306",
    "word307",
    "word308",
    "word309",
    "word310",
    "word311",
    "word312",
    "word313",
    "word314",
    "word315",
    "word316",
    "word317",
    "word318",
    "word319",
    "word320",
    "word321",
    "word322",
    "word323",
    "word324",
    "word325",
    "word326",
    "word327",
    "word328",
    "word329",
    "word330",
    "word331",
    "word332",
    "word333",
    "word334",
    "word335",
    "word336",
    "word337",
    "word338",
    "word339",
    "word340",
    "word341",
    "word342",
    "word343",
    "word344",
    "word345",
    "word346",
    "word347",
    "word348",
    "word349",
    "word350",
    "word351",
    "word352",
    "word353",
    "word354",
    "word355",
    "word356",
    "word357",
    "word358",
    "word359",
    "word360",
    "word361",
    "word362",
    "word363",
    "word364",
    "word365",
    "word366",
    "word367",
    "word368",
    "word369",
    "word370",
    "word371",
    "word372",
    "word373",
    "word374",
    "word375",
    "word376",
    "word377",
    "word378",
    "word379",
    "word380",
    "word381",
    "word382",
    "word383",
    "word384",
    "word385",
    "word386",
    "word387",
    "word388",
    "word389",
    "word390",
    "word391",
    "word392",
    "word393",
    "word394",
    "word395",
    "word396",
    "word397",
    "word398",
    "word399",
    "word400",
    "word401",
    "word402",
    "word403",
    "word404",
    "word405",
    "word406",
    "word407",
    "word408",
    "word409",
    "word410",
    "word411",
    "word412",
    "word413",
    "word414",
    "word415",
    "word416",
    "word417",
    "word418",
    "word419",
    "word420",
    "word421",
    "word422",
    "word423",
    "word424",
    "word425",
    "word426",
    "word427",
    "word428",
    "word429",
    "word430",
    "word431",
    "word432",
    "word433",
    "word434",
    "word435",
    "word436",
    "word437",
    "word438",
    "word439",
    "word440",
    "word441",
    "word442",
    "word443",
    "word444",
    "word445",
    "word446",
    "word447",
    "word448",
    "word449",
    "word450",
    "word451",
    "word452",
    "word453",
    "word454",
    "word455",
    "word456",
    "word457",
    "word458",
    "word459",
    "word460",
    "word461",
    "word462",
    "word463",
    "word464",
    "word465",
    "word466",
    "word467",
    "word468",
    "word469",
    "word470",
    "word471",
    "word472",
    "word473",
    "word474",
    "word475",
    "word476",
    "word477",
    "word478",
    "word479",
    "word480",
    "word481",
    "word482",
    "word483",
    "word484",
    "word485",
    "word486",
    "word487",
    "word488",
    "word489",
    "word490",
    "word491",
    "word492",
    "word493",
    "word494",
    "word495",
    "word496",
    "word497",
    "word498",
    "word499",
    "word500",
    "word501",
    "word502",
    "word503",
    "word504",
    "word505",
    "word506",
    "word507",
    "word508",
    "word509",
    "word510",
    "word511",
    "word512",
    "word513",
    "word514",
    "word515",
    "word516",
    "word517",
    "word518",
    "word519",
    "word520",
    "word521",
    "word522",
    "word523",
    "word524",
    "word525",
    "word526",
    "word527",
    "word528",
    "word529",
    "word530",
    "word531",
    "word532",
    "word533",
    "word534",
    "word535",
    "word536",
    "word537",
    "word538",
    "word539",
    "word540",
    "word541",
    "word542",
    "word543",
    "word544",
    "word545",
    "word546",
    "word547",
    "word548",
    "word549",
    "word550",
    "word551",
    "word552",
    "word553",
    "word554",
    "word555",
    "word556",
    "word557",
    "word558",
    "word559",
    "word560",
    "word561",
    "word562",
    "word563",
    "word564",
    "word565",
    "word566",
    "word567",
    "word568",
    "word569",
    "word570",
    "word571",
    "word572",
    "word573",
    "word574",
    "word575",
    "word576",
    "word577",
    "word578",
    "word579",
    "word580",
    "word581",
    "word582",
    "word583",
    "word584",
    "word585",
    "word586",
    "word587",
    "word588",
    "word589",
    "word590",
    "word591",
    "word592",
    "word593",
    "word594",
    "word595",
    "word596",
    "word597",
    "word598",
    "word599",
    "word600",
    "word601",
    "word602",
    "word603",
    "word604",
    "word605",
    "word606",
    "word607",
    "word608",
    "word609",
    "word610",
    "word611",
    "word612",
    "word613",
    "word614",
    "word615",
    "word616",
    "word617",
    "word618",
    "word619",
    "word620",
    "word621",
    "word622",
    "word623",
    "word624",
    "word625",
    "word626",
    "word627",
    "word628",
    "word629",
    "word630",
    "word631",
    "word632",
    "word633",
    "word634",
    "word635",
    "word636",
    "word637",
    "word638",
    "word639",
    "word640",
    "word641",
    "word642",
    "word643",
    "word644",
    "word645",
    "word646",
    "word647",
    "word648",
    "word649",
    "word650",
    "word651",
    "word652",
    "word653",
    "word654",
    "word655",
    "word656",
    "word657",
    "word658",
    "word659",
    "word660",
    "word661",
    "word662",
    "word663",
    "word664",
    "word665",
    "word666",
    "word667",
    "word668",
    "word669",
    "word670",
    "word671",
    "word672",
    "word673",
    "word674",
    "word675",
    "word676",
    "word677",
    "word678",
    "word679",
    "word680",
    "word681",
    "word682",
    "word683",
    "word684",
    "word685",
    "word686",
    "word687",
    "word688",
    "word689",
    "word690",
    "word691",
    "word692",
    "word693",
    "word694",
    "word695",
    "word696",
    "word697",
    "word698",
    "word699",
    "word700",
    "word701",
    "word702",
    "word703",
    "word704",
    "word705",
    "word706",
    "word707",
    "word708",
    "word709",
    "word710",
    "word711",
    "word712",
    "word713",
    "word714",
    "word715",
    "word716",
    "word717",
    "word718",
    "word719",
    "word720",
    "word721",
    "word722",
    "word723",
    "word724",
    "word725",
    "word726",
    "word727",
    "word728",
    "word729",
    "word730",
    "word731",
    "word732",
    "word733",
    "word734",
    "word735",
    "word736",
    "word737",
    "word738",
    "word739",
    "word740",
    "word741",
    "word742",
    "word743",
    "word744",
    "word745",
    "word746",
    "word747",
    "word748",
    "word749",
    "word750",
    "word751",
    "word752",
    "word753",
    "word754",
    "word755",
    "word756",
    "word757",
    "word758",
    "word759",
    "word760",
    "word761",
    "word762",
    "word763",
    "word764",
    "word765",
    "word766",
    "word767",
    "word768",
    "word769",
    "word770",
    "word771",
    "word772",
    "word773",
    "word774",
    "word775",
    "word776",
    "word777",
    "word778",
    "word779",
    "word780",
    "word781",
    "word782",
    "word783",
    "word784",
    "word785",
    "word786",
    "word787",
    "word788",
    "word789",
    "word790",
    "word791",
    "word792",
    "word793",
    "word794",
    "word795",
    "word796",
    "word797",
    "word798",
    "word799",
    "word800",
    "word801",
    "word802",
    "word803",
    "word804",
    "word805",
    "word806",
    "word807",
    "word808",
    "word809",
    "word810",
    "word811",
    "word812",
    "word813",
    "word814",
    "word815",
    "word816",
    "word817",
    "word818",
    "word819",
    "word820",
    "word821",
    "word822",
    "word823",
    "word824",
    "word825",
    "word826",
    "word827",
    "word828",
    "word829",
    "word830",
    "word831",
    "word832",
    "word833",
    "word834",
    "word835",
    "word836",
    "word837",
    "word838",
    "word839",
    "word840",
    "word841",
    "word842",
    "word843",
    "word844",
    "word845",
    "word846",
    "word847",
    "word848",
    "word849",
    "word850",
    "word851",
    "word852",
    "word853",
    "word854",
    "word855",
    "word856",
    "word857",
    "word858",
    "word859",
    "word860",
    "word861",
    "word862",
    "word863",
    "word864",
    "word865",
    "word866",
    "word867",
    "word868",
    "word869",
    "word870",
    "word871",
    "word872",
    "word873",
    "word874",
    "word875",
    "word876",
    "word877",
    "word878",
    "word879",
    "word880",
    "word881",
    "word882",
    "word883",
    "word884",
    "word885",
    "word886",
    "word887",
    "word888",
    "word889",
    "word890",
    "word891",
    "word892",
    "word893",
    "word894",
    "word895",
    "word896",
    "word897",
    "word898",
    "word899",
    "word900",
    "word901",
    "word902",
    "word903",
    "word904",
    "word905",
    "word906",
    "word907",
    "word908",
    "word909",
    "word910",
    "word911",
    "word912",
    "word913",
    "word914",
    "word915",
    "word916",
    "word917",
    "word918",
    "word919",
    "word920",
    "word921",
    "word922",
    "word923",
    "word924",
    "word925",
    "word926",
    "word927",
    "word928",
    "word929",
    "word930",
    "word931",
    "word932",
    "word933",
    "word934"
];

// 2. 不规则词形还原映射表 (Exception Lexicon)
export const IRREGULAR_MAP: Record<string, string> = {
    "am": "be",
    "is": "be",
    "are": "be",
    "was": "be",
    "were": "be",
    "been": "be",
    "being": "be",
    "went": "go",
    "gone": "go",
    "goes": "go",
    "did": "do",
    "done": "do",
    "does": "do",
    "had": "have",
    "has": "have",
    "having": "have",
    "saw": "see",
    "seen": "see",
    "sees": "see",
    "wrote": "write",
    "written": "write",
    "writes": "write",
    "took": "take",
    "taken": "take",
    "takes": "take",
    "made": "make",
    "makes": "make",
    "came": "come",
    "comes": "come",
    "gave": "give",
    "given": "give",
    "gives": "give",
    "found": "find",
    "finds": "find",
    "thought": "think",
    "thinks": "think",
    "told": "tell",
    "tells": "tell",
    "said": "say",
    "says": "say",
    "brought": "bring",
    "brings": "bring",
    "bought": "buy",
    "buys": "buy",
    "kept": "keep",
    "keeps": "keep",
    "held": "hold",
    "holds": "hold",
    "stood": "stand",
    "stands": "stand",
    "understood": "understand",
    "understands": "understand",
    "met": "meet",
    "meets": "meet",
    "ran": "run",
    "runned": "run",
    "runs": "run",
    "sat": "sit",
    "sits": "sit",
    "spoke": "speak",
    "spoken": "speak",
    "speaks": "speak",
    "spent": "spend",
    "spends": "spend",
    "lost": "lose",
    "loses": "lose",
    "fell": "fall",
    "fallen": "fall",
    "falls": "fall",
    "sent": "send",
    "sends": "send",
    "built": "build",
    "builds": "build",
    "left": "leave",
    "leaves": "leave",
    "grew": "grow",
    "grown": "grow",
    "grows": "grow",
    "drew": "draw",
    "drawn": "draw",
    "draws": "draw",
    "began": "begin",
    "begun": "begin",
    "begins": "begin",
    "showed": "show",
    "shown": "show",
    "shows": "show",
    "knew": "know",
    "known": "know",
    "knows": "know",
    "swam": "swim",
    "swum": "swim",
    "swims": "swim",
    "children": "child",
    "men": "man",
    "women": "woman",
    "feet": "foot",
    "teeth": "tooth",
    "mice": "mouse",
    "geese": "goose",
    "better": "good",
    "best": "good",
    "worse": "bad",
    "worst": "bad",
    "less": "little",
    "least": "little",
    "more": "much",
    "most": "much"
};

// 3. 常用高频词组短语表 (F10 前向最大匹配基石)
export const COMMON_PHRASES: string[] = [
    "look after",
    "look for",
    "look forward to",
    "look up",
    "look out",
    "look into",
    "take care of",
    "take part in",
    "take place",
    "take off",
    "take over",
    "take action",
    "deal with",
    "cope with",
    "agree with",
    "depend on",
    "rely on",
    "focus on",
    "because of",
    "instead of",
    "in front of",
    "in order to",
    "in spite of",
    "on account of",
    "by means of",
    "by virtue of",
    "by way of",
    "in terms of",
    "as a result of",
    "as well as",
    "as far as",
    "as soon as",
    "so as to",
    "according to",
    "due to",
    "thanks to",
    "prior to",
    "pointing out",
    "put off",
    "put on",
    "put out",
    "put up with",
    "put forward",
    "give up",
    "give in",
    "give rise to",
    "run out of",
    "run into",
    "run away",
    "get up",
    "get on",
    "get off",
    "get along with",
    "get rid of",
    "set up",
    "set off",
    "set out",
    "bring about",
    "bring up",
    "bring out",
    "carry out",
    "carry on",
    "call off",
    "call for",
    "call on",
    "point out",
    "make sure",
    "find out",
    "turn out to be"
];

// 4. 内置前 200 核心词的极简离线字典包 (F11 降级支持)
export interface DictEntry {
    phonetic: string;
    trans: string;
}
export const OFFLINE_DICT: Record<string, DictEntry> = {
    "the": {
        "phonetic": "ðə",
        "trans": "art. 这；那"
    },
    "of": {
        "phonetic": "ɒv",
        "trans": "prep. …的；由…制成的"
    },
    "and": {
        "phonetic": "ænd",
        "trans": "conj. 和，与"
    },
    "to": {
        "phonetic": "tuː",
        "trans": "prep. 向，朝；达到"
    },
    "a": {
        "phonetic": "eɪ",
        "trans": "art. 一，一个"
    },
    "in": {
        "phonetic": "ɪn",
        "trans": "prep. 在…里；在…期间"
    },
    "for": {
        "phonetic": "fɔː",
        "trans": "prep. 为了；给；代表"
    },
    "is": {
        "phonetic": "ɪz",
        "trans": "v. 是（be的单数第三人称现在时）"
    },
    "on": {
        "phonetic": "ɒn",
        "trans": "prep. 在…之上；关于"
    },
    "that": {
        "phonetic": "ðæt",
        "trans": "pron. 那，那个；conj. 引导从句"
    },
    "by": {
        "phonetic": "baɪ",
        "trans": "prep. 被，由；通过；在…旁边"
    },
    "this": {
        "phonetic": "ðɪs",
        "trans": "pron. 这，这个"
    },
    "with": {
        "phonetic": "wɪð",
        "trans": "prep. 具有；和…一起；用"
    },
    "i": {
        "phonetic": "aɪ",
        "trans": "pron. 我"
    },
    "you": {
        "phonetic": "juː",
        "trans": "pron. 你，你们"
    },
    "it": {
        "phonetic": "ɪt",
        "trans": "pron. 它"
    },
    "not": {
        "phonetic": "nɒt",
        "trans": "adv. 不，没有"
    },
    "or": {
        "phonetic": "ɔː",
        "trans": "conj. 或者；否则"
    },
    "be": {
        "phonetic": "biː",
        "trans": "v. 是；存在"
    },
    "are": {
        "phonetic": "ɑː",
        "trans": "v. 是（be的复数现在时）"
    },
    "from": {
        "phonetic": "frɒm",
        "trans": "prep. 来自，从"
    },
    "at": {
        "phonetic": "æt",
        "trans": "prep. 在…地点；在…时刻"
    },
    "as": {
        "phonetic": "æz",
        "trans": "adv. 同样地；prep. 作为；conj. 当…时"
    },
    "your": {
        "phonetic": "jɔː",
        "trans": "pron. 你的，你们的"
    },
    "all": {
        "phonetic": "ɔːl",
        "trans": "adj. 全部的；pron. 所有人/事"
    },
    "have": {
        "phonetic": "hæv",
        "trans": "v. 有；吃；让"
    },
    "new": {
        "phonetic": "njuː",
        "trans": "adj. 新的；新鲜的"
    },
    "more": {
        "phonetic": "mɔː",
        "trans": "adv. 更多；adj. 更多的"
    },
    "an": {
        "phonetic": "æn",
        "trans": "art. 一（元音前）"
    },
    "was": {
        "phonetic": "wɒz",
        "trans": "v. 是（be的过去单数第一、三人称）"
    },
    "we": {
        "phonetic": "wiː",
        "trans": "pron. 我们"
    },
    "will": {
        "phonetic": "wɪl",
        "trans": "aux. 将要；n. 意志，遗嘱"
    },
    "can": {
        "phonetic": "kæn",
        "trans": "aux. 能，可以；n. 罐头"
    },
    "about": {
        "phonetic": "əˈbaʊt",
        "trans": "prep. 关于；大约"
    },
    "if": {
        "phonetic": "ɪf",
        "trans": "conj. 如果；是否"
    },
    "my": {
        "phonetic": "maɪ",
        "trans": "pron. 我的"
    },
    "has": {
        "phonetic": "hæz",
        "trans": "v. 有（have的单数第三人称现在时）"
    },
    "but": {
        "phonetic": "bʌt",
        "trans": "conj. 但是；而"
    },
    "our": {
        "phonetic": "ˈaʊə",
        "trans": "pron. 我们的"
    },
    "one": {
        "phonetic": "wʌn",
        "trans": "num. 一；pron. 某一个人/物"
    },
    "other": {
        "phonetic": "ˈʌðə",
        "trans": "adj. 其他的；pron. 另一个"
    },
    "do": {
        "phonetic": "duː",
        "trans": "v. 做，干；aux. 助动词"
    },
    "no": {
        "phonetic": "nəʊ",
        "trans": "adv. 不，没有；adj. 没有的"
    },
    "information": {
        "phonetic": "ˌɪnfəˈmeɪʃn",
        "trans": "n. 信息，消息，通知"
    },
    "time": {
        "phonetic": "taɪm",
        "trans": "n. 时间；次数；倍数"
    },
    "they": {
        "phonetic": "ðeɪ",
        "trans": "pron. 他们，她们，它们"
    },
    "he": {
        "phonetic": "hiː",
        "trans": "pron. 他"
    },
    "up": {
        "phonetic": "ʌp",
        "trans": "adv. 向上；在上方"
    },
    "may": {
        "phonetic": "meɪ",
        "trans": "aux. 也许，可以；n. 五月"
    },
    "what": {
        "phonetic": "wɒt",
        "trans": "pron. 什么"
    },
    "which": {
        "phonetic": "wɪtʃ",
        "trans": "pron. 哪个，哪些"
    },
    "their": {
        "phonetic": "ðeə",
        "trans": "pron. 他们的，她们的"
    },
    "out": {
        "phonetic": "aʊt",
        "trans": "adv. 向外；出来；彻底"
    },
    "use": {
        "phonetic": "juːz",
        "trans": "v. 使用，利用；n. 用途"
    },
    "any": {
        "phonetic": "ˈeni",
        "trans": "adj. 任何的；pron. 任何"
    },
    "there": {
        "phonetic": "ðeə",
        "trans": "adv. 在那里；there be 结构"
    },
    "see": {
        "phonetic": "siː",
        "trans": "v. 看见；明白"
    },
    "only": {
        "phonetic": "ˈəʊnli",
        "trans": "adv. 只，仅仅；adj. 唯一的"
    },
    "so": {
        "phonetic": "səʊ",
        "trans": "adv. 如此，这么；conj. 所以"
    },
    "his": {
        "phonetic": "hɪz",
        "trans": "pron. 他的"
    },
    "when": {
        "phonetic": "wen",
        "trans": "conj. 当…时；adv. 什么时候"
    },
    "here": {
        "phonetic": "hɪə",
        "trans": "adv. 在这里，到这里"
    },
    "business": {
        "phonetic": "ˈbɪznəs",
        "trans": "n. 商业，买卖；事务"
    },
    "who": {
        "phonetic": "huː",
        "trans": "pron. 谁，什么人"
    },
    "web": {
        "phonetic": "web",
        "trans": "n. 网，蛛网；互联网"
    },
    "also": {
        "phonetic": "ˈɔːlsəʊ",
        "trans": "adv. 而且，也"
    },
    "now": {
        "phonetic": "naʊ",
        "trans": "adv. 现在，立刻"
    },
    "help": {
        "phonetic": "help",
        "trans": "v. & n. 帮助，援助"
    },
    "get": {
        "phonetic": "ɡet",
        "trans": "v. 得到；到达；变得"
    },
    "view": {
        "phonetic": "vjuː",
        "trans": "n. 视野，观点；v. 观察"
    },
    "online": {
        "phonetic": "ˌɒnˈlaɪn",
        "trans": "adj. 在线的，联机的"
    },
    "first": {
        "phonetic": "fɜːst",
        "trans": "num. 第一；adv. 首先"
    },
    "been": {
        "phonetic": "biːn",
        "trans": "v. be的过去分词"
    },
    "would": {
        "phonetic": "wʊd",
        "trans": "aux. 将，会；愿意"
    },
    "how": {
        "phonetic": "haʊ",
        "trans": "adv. 怎样，如何；多么"
    },
    "were": {
        "phonetic": "wɜː",
        "trans": "v. be的过去式复数"
    },
    "me": {
        "phonetic": "miː",
        "trans": "pron. 我（宾格）"
    },
    "some": {
        "phonetic": "sʌm",
        "trans": "adj. 一些，若干；某些"
    },
    "these": {
        "phonetic": "ðiːz",
        "trans": "pron. 这些"
    },
    "like": {
        "phonetic": "laɪk",
        "trans": "v. 喜欢；prep. 像，如同"
    },
    "find": {
        "phonetic": "faɪnd",
        "trans": "v. 找到，发现；觉得"
    },
    "back": {
        "phonetic": "bæk",
        "trans": "adv. 向后；回来；n. 背部"
    },
    "people": {
        "phonetic": "ˈpiːpl",
        "trans": "n. 人，人们；民族"
    },
    "had": {
        "phonetic": "hæd",
        "trans": "v. have的过去式和过去分词"
    },
    "list": {
        "phonetic": "lɪst",
        "trans": "n. 目录，列表；v. 列出"
    },
    "name": {
        "phonetic": "neɪm",
        "trans": "n. 名字，名称；v. 命名"
    },
    "just": {
        "phonetic": "dʒʌst",
        "trans": "adv. 刚才；仅仅；非常"
    },
    "over": {
        "phonetic": "ˈəʊvə",
        "trans": "prep. 在…上方；越过；超过"
    },
    "state": {
        "phonetic": "steɪt",
        "trans": "n. 状态；国家；州；v. 陈述"
    },
    "year": {
        "phonetic": "jɪə",
        "trans": "n. 年，年度"
    },
    "day": {
        "phonetic": "deɪ",
        "trans": "n. 白天，一天"
    },
    "into": {
        "phonetic": "ˈɪntə",
        "trans": "prep. 进入…中；成为"
    },
    "two": {
        "phonetic": "tuː",
        "trans": "num. 二，两个"
    },
    "go": {
        "phonetic": "ɡəʊ",
        "trans": "v. 去，走；运转"
    },
    "work": {
        "phonetic": "wɜːk",
        "trans": "n. 工作；著作；v. 工作"
    },
    "last": {
        "phonetic": "lɑːst",
        "trans": "adj. 最后的；最近的；v. 持续"
    },
    "most": {
        "phonetic": "məʊst",
        "trans": "adj. 最多的；adv. 最，非常"
    },
    "make": {
        "phonetic": "meɪk",
        "trans": "v. 制造；做；使得"
    },
    "them": {
        "phonetic": "ðem",
        "trans": "pron. 他们/她们/它们（宾格）"
    },
    "should": {
        "phonetic": "ʃʊd",
        "trans": "aux. 应该，应当"
    },
    "system": {
        "phonetic": "ˈsɪstəm",
        "trans": "n. 系统，体系，制度"
    },
    "after": {
        "phonetic": "ˈɑːftə",
        "trans": "prep. 在…后面；在…之后"
    },
    "best": {
        "phonetic": "best",
        "trans": "adj. 最好的；adv. 最好地"
    },
    "good": {
        "phonetic": "ɡʊd",
        "trans": "adj. 好的，有益的"
    },
    "well": {
        "phonetic": "wel",
        "trans": "adv. 好地；adj. 健康的；n. 井"
    },
    "where": {
        "phonetic": "weə",
        "trans": "adv. 在哪里；conj. 在…的地方"
    },
    "high": {
        "phonetic": "haɪ",
        "trans": "adj. 高的；高尚的；adv. 高高地"
    },
    "school": {
        "phonetic": "skuːl",
        "trans": "n. 学校；学派"
    },
    "through": {
        "phonetic": "θruː",
        "trans": "prep. 穿过，通过；凭借"
    },
    "each": {
        "phonetic": "iːtʃ",
        "trans": "adj. & pron. 每个，各自"
    },
    "she": {
        "phonetic": "ʃiː",
        "trans": "pron. 她"
    },
    "order": {
        "phonetic": "ˈɔːdə",
        "trans": "n. 顺序；命令；订购；v. 命令"
    },
    "very": {
        "phonetic": "ˈveri",
        "trans": "adv. 非常，极"
    },
    "book": {
        "phonetic": "bʊk",
        "trans": "n. 书；v. 预订"
    },
    "company": {
        "phonetic": "ˈkʌmpəni",
        "trans": "n. 公司；伙伴；交往"
    },
    "read": {
        "phonetic": "riːd",
        "trans": "v. 阅读；朗读"
    },
    "group": {
        "phonetic": "ɡruːp",
        "trans": "n. 组，群；v. 分组"
    },
    "need": {
        "phonetic": "niːd",
        "trans": "v. & n. 需要，必须"
    },
    "many": {
        "phonetic": "ˈmeni",
        "trans": "adj. 许多的；pron. 许多人/物"
    },
    "user": {
        "phonetic": "ˈjuːzə",
        "trans": "n. 用户，使用者"
    },
    "said": {
        "phonetic": "sed",
        "trans": "v. say的过去式和过去分词"
    },
    "does": {
        "phonetic": "dʌz",
        "trans": "v. do的单数第三人称现在时"
    },
    "set": {
        "phonetic": "set",
        "trans": "v. 放，安置；设置；n. 一套"
    },
    "under": {
        "phonetic": "ˈʌndə",
        "trans": "prep. 在…下面；在…领导下"
    },
    "general": {
        "phonetic": "ˈdʒenrəl",
        "trans": "adj. 一般的，总的；n. 将军"
    },
    "research": {
        "phonetic": "rɪˈsɜːtʃ",
        "trans": "n. & v. 研究，调查"
    },
    "life": {
        "phonetic": "laɪf",
        "trans": "n. 生命；生活；一生"
    },
    "know": {
        "phonetic": "nəʊ",
        "trans": "v. 知道，认识；了解"
    },
    "way": {
        "phonetic": "weɪ",
        "trans": "n. 道路；方法；方向"
    },
    "could": {
        "phonetic": "kʊd",
        "trans": "aux. can的过去式；可能"
    },
    "great": {
        "phonetic": "ɡreɪt",
        "trans": "adj. 伟大的；重大的；极好的"
    },
    "must": {
        "phonetic": "mʌst",
        "trans": "aux. 必须，应当；必定"
    },
    "write": {
        "phonetic": "raɪt",
        "trans": "v. 写，书写，写作"
    }
};

// 5. 中译英反向索引 (中文词汇 → 英文 Lemma[])
export const REVERSE_INDEX: Record<string, string[]> = {
    "这": [
        "the",
        "this"
    ],
    "那": [
        "the",
        "that"
    ],
    "的": [
        "of"
    ],
    "由": [
        "of",
        "by"
    ],
    "制成的": [
        "of"
    ],
    "和": [
        "and",
        "with"
    ],
    "与": [
        "and"
    ],
    "向": [
        "to"
    ],
    "朝": [
        "to"
    ],
    "达到": [
        "to"
    ],
    "一": [
        "a",
        "an",
        "one"
    ],
    "一个": [
        "a"
    ],
    "在": [
        "in",
        "on",
        "by",
        "at",
        "over",
        "after",
        "where",
        "under"
    ],
    "里": [
        "in"
    ],
    "期间": [
        "in"
    ],
    "为了": [
        "for"
    ],
    "给": [
        "for"
    ],
    "代表": [
        "for"
    ],
    "是": [
        "is",
        "be",
        "are",
        "was"
    ],
    "的单数第三人称现在时": [
        "is",
        "has",
        "does"
    ],
    "之上": [
        "on"
    ],
    "关于": [
        "on",
        "about"
    ],
    "那个": [
        "that"
    ],
    "引导从句": [
        "that"
    ],
    "被": [
        "by"
    ],
    "通过": [
        "by",
        "through"
    ],
    "旁边": [
        "by"
    ],
    "这个": [
        "this"
    ],
    "具有": [
        "with"
    ],
    "一起": [
        "with"
    ],
    "用": [
        "with"
    ],
    "我": [
        "i",
        "me"
    ],
    "你": [
        "you"
    ],
    "你们": [
        "you"
    ],
    "它": [
        "it"
    ],
    "不": [
        "not",
        "no"
    ],
    "没有": [
        "not",
        "no"
    ],
    "或者": [
        "or"
    ],
    "否则": [
        "or"
    ],
    "存在": [
        "be"
    ],
    "的复数现在时": [
        "are"
    ],
    "来自": [
        "from"
    ],
    "从": [
        "from"
    ],
    "地点": [
        "at"
    ],
    "时刻": [
        "at"
    ],
    "同样地": [
        "as"
    ],
    "作为": [
        "as"
    ],
    "当": [
        "as",
        "when"
    ],
    "时": [
        "as",
        "when"
    ],
    "你的": [
        "your"
    ],
    "你们的": [
        "your"
    ],
    "全部的": [
        "all"
    ],
    "所有人": [
        "all"
    ],
    "事": [
        "all"
    ],
    "有": [
        "have",
        "has"
    ],
    "吃": [
        "have"
    ],
    "让": [
        "have"
    ],
    "新的": [
        "new"
    ],
    "新鲜的": [
        "new"
    ],
    "更多": [
        "more"
    ],
    "更多的": [
        "more"
    ],
    "元音前": [
        "an"
    ],
    "的过去单数第一": [
        "was"
    ],
    "三人称": [
        "was"
    ],
    "我们": [
        "we"
    ],
    "将要": [
        "will"
    ],
    "意志": [
        "will"
    ],
    "遗嘱": [
        "will"
    ],
    "能": [
        "can"
    ],
    "可以": [
        "can",
        "may"
    ],
    "罐头": [
        "can"
    ],
    "大约": [
        "about"
    ],
    "如果": [
        "if"
    ],
    "是否": [
        "if"
    ],
    "我的": [
        "my"
    ],
    "但是": [
        "but"
    ],
    "而": [
        "but"
    ],
    "我们的": [
        "our"
    ],
    "某一个人": [
        "one"
    ],
    "物": [
        "one",
        "many"
    ],
    "其他的": [
        "other"
    ],
    "另一个": [
        "other"
    ],
    "做": [
        "do",
        "make"
    ],
    "干": [
        "do"
    ],
    "助动词": [
        "do"
    ],
    "没有的": [
        "no"
    ],
    "信息": [
        "information"
    ],
    "消息": [
        "information"
    ],
    "通知": [
        "information"
    ],
    "时间": [
        "time"
    ],
    "次数": [
        "time"
    ],
    "倍数": [
        "time"
    ],
    "他们": [
        "they",
        "them"
    ],
    "她们": [
        "they",
        "them"
    ],
    "它们": [
        "they",
        "them"
    ],
    "他": [
        "he"
    ],
    "向上": [
        "up"
    ],
    "在上方": [
        "up"
    ],
    "也许": [
        "may"
    ],
    "五月": [
        "may"
    ],
    "什么": [
        "what"
    ],
    "哪个": [
        "which"
    ],
    "哪些": [
        "which"
    ],
    "他们的": [
        "their"
    ],
    "她们的": [
        "their"
    ],
    "向外": [
        "out"
    ],
    "出来": [
        "out"
    ],
    "彻底": [
        "out"
    ],
    "使用": [
        "use"
    ],
    "利用": [
        "use"
    ],
    "用途": [
        "use"
    ],
    "任何的": [
        "any"
    ],
    "任何": [
        "any"
    ],
    "在那里": [
        "there"
    ],
    "结构": [
        "there"
    ],
    "看见": [
        "see"
    ],
    "明白": [
        "see"
    ],
    "只": [
        "only"
    ],
    "仅仅": [
        "only",
        "just"
    ],
    "唯一的": [
        "only"
    ],
    "如此": [
        "so"
    ],
    "这么": [
        "so"
    ],
    "所以": [
        "so"
    ],
    "他的": [
        "his"
    ],
    "什么时候": [
        "when"
    ],
    "在这里": [
        "here"
    ],
    "到这里": [
        "here"
    ],
    "商业": [
        "business"
    ],
    "买卖": [
        "business"
    ],
    "事务": [
        "business"
    ],
    "谁": [
        "who"
    ],
    "什么人": [
        "who"
    ],
    "网": [
        "web"
    ],
    "蛛网": [
        "web"
    ],
    "互联网": [
        "web"
    ],
    "而且": [
        "also"
    ],
    "也": [
        "also"
    ],
    "现在": [
        "now"
    ],
    "立刻": [
        "now"
    ],
    "帮助": [
        "help"
    ],
    "援助": [
        "help"
    ],
    "得到": [
        "get"
    ],
    "到达": [
        "get"
    ],
    "变得": [
        "get"
    ],
    "视野": [
        "view"
    ],
    "观点": [
        "view"
    ],
    "观察": [
        "view"
    ],
    "在线的": [
        "online"
    ],
    "联机的": [
        "online"
    ],
    "第一": [
        "first"
    ],
    "首先": [
        "first"
    ],
    "的过去分词": [
        "been"
    ],
    "将": [
        "would"
    ],
    "会": [
        "would"
    ],
    "愿意": [
        "would"
    ],
    "怎样": [
        "how"
    ],
    "如何": [
        "how"
    ],
    "多么": [
        "how"
    ],
    "的过去式复数": [
        "were"
    ],
    "宾格": [
        "me",
        "them"
    ],
    "一些": [
        "some"
    ],
    "若干": [
        "some"
    ],
    "某些": [
        "some"
    ],
    "这些": [
        "these"
    ],
    "喜欢": [
        "like"
    ],
    "像": [
        "like"
    ],
    "如同": [
        "like"
    ],
    "找到": [
        "find"
    ],
    "发现": [
        "find"
    ],
    "觉得": [
        "find"
    ],
    "向后": [
        "back"
    ],
    "回来": [
        "back"
    ],
    "背部": [
        "back"
    ],
    "人": [
        "people"
    ],
    "人们": [
        "people"
    ],
    "民族": [
        "people"
    ],
    "的过去式和过去分词": [
        "had",
        "said"
    ],
    "目录": [
        "list"
    ],
    "列表": [
        "list"
    ],
    "列出": [
        "list"
    ],
    "名字": [
        "name"
    ],
    "名称": [
        "name"
    ],
    "命名": [
        "name"
    ],
    "刚才": [
        "just"
    ],
    "非常": [
        "just",
        "most",
        "very"
    ],
    "上方": [
        "over"
    ],
    "越过": [
        "over"
    ],
    "超过": [
        "over"
    ],
    "状态": [
        "state"
    ],
    "国家": [
        "state"
    ],
    "州": [
        "state"
    ],
    "陈述": [
        "state"
    ],
    "年": [
        "year"
    ],
    "年度": [
        "year"
    ],
    "白天": [
        "day"
    ],
    "一天": [
        "day"
    ],
    "进入": [
        "into"
    ],
    "中": [
        "into"
    ],
    "成为": [
        "into"
    ],
    "二": [
        "two"
    ],
    "两个": [
        "two"
    ],
    "去": [
        "go"
    ],
    "走": [
        "go"
    ],
    "运转": [
        "go"
    ],
    "工作": [
        "work"
    ],
    "著作": [
        "work"
    ],
    "最后的": [
        "last"
    ],
    "最近的": [
        "last"
    ],
    "持续": [
        "last"
    ],
    "最多的": [
        "most"
    ],
    "最": [
        "most"
    ],
    "制造": [
        "make"
    ],
    "使得": [
        "make"
    ],
    "应该": [
        "should"
    ],
    "应当": [
        "should",
        "must"
    ],
    "系统": [
        "system"
    ],
    "体系": [
        "system"
    ],
    "制度": [
        "system"
    ],
    "后面": [
        "after"
    ],
    "之后": [
        "after"
    ],
    "最好的": [
        "best"
    ],
    "最好地": [
        "best"
    ],
    "好的": [
        "good"
    ],
    "有益的": [
        "good"
    ],
    "好地": [
        "well"
    ],
    "健康的": [
        "well"
    ],
    "井": [
        "well"
    ],
    "在哪里": [
        "where"
    ],
    "的地方": [
        "where"
    ],
    "高的": [
        "high"
    ],
    "高尚的": [
        "high"
    ],
    "高高地": [
        "high"
    ],
    "学校": [
        "school"
    ],
    "学派": [
        "school"
    ],
    "穿过": [
        "through"
    ],
    "凭借": [
        "through"
    ],
    "每个": [
        "each"
    ],
    "各自": [
        "each"
    ],
    "她": [
        "she"
    ],
    "顺序": [
        "order"
    ],
    "命令": [
        "order"
    ],
    "订购": [
        "order"
    ],
    "极": [
        "very"
    ],
    "书": [
        "book"
    ],
    "预订": [
        "book"
    ],
    "公司": [
        "company"
    ],
    "伙伴": [
        "company"
    ],
    "交往": [
        "company"
    ],
    "阅读": [
        "read"
    ],
    "朗读": [
        "read"
    ],
    "组": [
        "group"
    ],
    "群": [
        "group"
    ],
    "分组": [
        "group"
    ],
    "需要": [
        "need"
    ],
    "必须": [
        "need",
        "must"
    ],
    "许多的": [
        "many"
    ],
    "许多人": [
        "many"
    ],
    "用户": [
        "user"
    ],
    "使用者": [
        "user"
    ],
    "放": [
        "set"
    ],
    "安置": [
        "set"
    ],
    "设置": [
        "set"
    ],
    "一套": [
        "set"
    ],
    "下面": [
        "under"
    ],
    "领导下": [
        "under"
    ],
    "一般的": [
        "general"
    ],
    "总的": [
        "general"
    ],
    "将军": [
        "general"
    ],
    "研究": [
        "research"
    ],
    "调查": [
        "research"
    ],
    "生命": [
        "life"
    ],
    "生活": [
        "life"
    ],
    "一生": [
        "life"
    ],
    "知道": [
        "know"
    ],
    "认识": [
        "know"
    ],
    "了解": [
        "know"
    ],
    "道路": [
        "way"
    ],
    "方法": [
        "way"
    ],
    "方向": [
        "way"
    ],
    "的过去式": [
        "could"
    ],
    "可能": [
        "could"
    ],
    "伟大的": [
        "great"
    ],
    "重大的": [
        "great"
    ],
    "极好的": [
        "great"
    ],
    "必定": [
        "must"
    ],
    "写": [
        "write"
    ],
    "书写": [
        "write"
    ],
    "写作": [
        "write"
    ]
};
